//loaders
export const ERROR_DISPATCHED = 'ERROR_DISPATCHED';
export const ERROR_CLEANED = 'ERROR_CLEANED';

export const CLEAR = 'CLEAR';

export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RESPONSE_CHARACTERS = 'RESPONSE_CHARACTERS';
export const FAILED_CHARACTERS = 'FAILED_CHARACTERS';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const REQUEST_CHARACTER_DETAIL = 'REQUEST_CHARACTER_DETAIL';
export const RESPONSE_CHARACTER_DETAIL = 'RESPONSE_CHARACTER_DETAIL';